<?php if($this->displayNameUpdated){
	echo $this->alert('credential_has_been_changed','alert-success',false);
?>
<button class="btn btn-small btn-primary pull-right" type="button" data-dismiss="modal"><?=$this->translate('close_modal')?></button>
<?php }
else{
	echo $this->form($this->form,\TwbBundle\Form\View\Helper\TwbBundleForm::LAYOUT_HORIZONTAL,true);
?>
<script type="text/javascript">
	if(document.id){
		var oAuthAccessCredential = document.id('new_user_display_name');
		if(oAuthAccessCredential)oAuthAccessCredential.focus();
	}
</script>
<?php } ?>