<h3><?=$this->layout()->title?></h3>
<div class="row-fluid">
	<div class="span10">
		<dl class="dl-horizontal">
			<dt><?=$this->translate('email')?> :</dt>
			<dd><span id="authaccess_email_identity"><?=$this->authenticatedAuthAccess->getAuthAccessEmailIdentity()?></span> | <a href="#" onclick="oController.changeAuthAccessEmailIdentity();return false;"><?=$this->translate('change_email')?></a></dd>
			<dt><?=$this->translate('username')?> :</dt>
			<dd><span id="authaccess_username_identity"><?=$this->authenticatedAuthAccess->getAuthAccessUsernameIdentity()?></span> | <a href="#" onclick="oController.changeAuthAccessUsernameIdentity();return false;"><?=$this->translate('change_username')?></a></dd>
			<dt><?=$this->translate('credential')?> :</dt>
			<dd><a href="#" onclick="oController.changeAuthAccessCredential();return false;"><?=$this->translate('change_credential')?></a></dd>
			<dd>&nbsp;</dd>
			<dd>
				<a class="btn btn-small btn-danger" href="<?=$this->url('AccessControl/AuthAccess/RemoveAuthAccess')?>" onclick="return confirm(oController.translate('confirm_remove_auth_access'));">
					<i class="icon-warning-sign"></i>
					&nbsp;<?=$this->translate('remove_auth_access')?>
				</a>
			</dd>
		</dl>
	</div>
</div>
<div class="row-fluid" style="margin-bottom:10px;">
	<h3><?=$this->translate('latest_activity')?> : </h3>
    <table class="table table-striped">
    	<thead>
    		<tr>
				<th><?=$this->translate('date_time')?></th>
				<th><?=$this->translate('ip')?></th>
				<th><?=$this->translate('access_type')?></th>
    		</tr>
    	</thead>
<?php
foreach($this->latestActivityLogs as $oLog){
	if(($oRequestHeaders = $oLog->getLogRequestHeaders()) && ($oUserAgent = $oRequestHeaders->get('user-agent'))){
		$oUserAgentInfos = $this->get_browser($oUserAgent);
		$sDevice = $oUserAgentInfos->platform?:'';
		if($oUserAgentInfos->parent)$sDevice .= ($sDevice?' / ':'').$oUserAgentInfos->parent;
	}

	if(($sIPAdress = $oLog->getLogIPAddress()) && $oLog->getLogSessionId() === $this->currentSessionId)$sIPAdress .= ' ('.$this->translate('current_session').')';
?>
		<tr>
			<td><?=$this->dateFormat($oLog->getEntityCreate(),\IntlDateFormatter::MEDIUM,\IntlDateFormatter::MEDIUM)?></td>
			<td><?=empty($sIPAdress)?'-':$sIPAdress?></td>
			<th><?=empty($sDevice)?'-':$sDevice?></th>
		</tr>
<?php } ?>
    </table>
</div>