<h3><?=$this->layout()->title?></h3>
<div class="row-fluid" style="margin-bottom:10px;">
<div class="span10">
		<dl class="dl-horizontal">
			<dt><?=$this->translate('email')?> :</dt>
			<dd><?=$this->authenticatedAuthAccess->getAuthAccessEmailIdentity()?> | <a href="#" onclick="oController.changeAuthAccessEmailIdentity();return false;"><?=$this->translate('change_email')?></a></dd>
			<dt><?=$this->translate('username')?> :</dt>
			<dd><?=$this->authenticatedAuthAccess->getAuthAccessUsernameIdentity()?> | <a href="#" onclick="oController.changeAuthAccessUsernameIdentity();return false;"><?=$this->translate('change_username')?></a></dd>
			<dt><?=$this->translate('credential')?> :</dt>
			<dd><a href="#" onclick="oController.changeAuthAccessCredential();return false;"><?=$this->translate('change_credential')?></a></dd>
		</dl>
	</div>
</div>