<h3><?=$this->layout()->title?></h3>
<div class="row-fluid" style="margin-bottom:10px;">
	<div class="span10">
		<dl class="dl-horizontal">
			<dt><?=$this->translate('email')?> :</dt>
			<dd><span id="authaccess_email_identity"><?=$this->authenticatedAuthAccess->getAuthAccessEmailIdentity()?></span> | <a href="#" onclick="oController.changeAuthAccessEmailIdentity();return false;"><?=$this->translate('change_email')?></a></dd>
			<dt><?=$this->translate('username')?> :</dt>
			<dd><span id="authaccess_username_identity"><?=$this->authenticatedAuthAccess->getAuthAccessUsernameIdentity()?></span> | <a href="#" onclick="oController.changeAuthAccessUsernameIdentity();return false;"><?=$this->translate('change_username')?></a></dd>
			<dt><?=$this->translate('credential')?> :</dt>
			<dd><a href="#" onclick="oController.changeAuthAccessCredential();return false;"><?=$this->translate('change_credential')?></a></dd>
		</dl>
	</div>
	<div class="pull-right">
		<a class="btn btn-small btn-danger" href="<?=$this->url('AccessControl/AuthAccess/RemoveAuthAccess')?>" onclick="return confirm(oController.translate('confirm_remove_auth_access'));">
			<i class="icon-warning-sign"></i>
			&nbsp;<?=$this->translate('remove_auth_access')?>
		</a>
	</div>
</div>