language: php

php:
 - "5.4"

before_install:
# Set the GitHub OAuth token to make use of the 6000 per hour rate limit
 - mkdir -p ~/.composer
 - cp .travis.composer.json ~/.composer/config.json
# Update composer
 - composer self-update
# Install project
 - composer install --dev -o
#deploy module
 - mkdir ../deploy
 - php ./vendor/bin/deploy_module.php -d ../deploy -v
# Install php packages
  - "sudo apt-get update > /dev/null"
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl
# Create VirtualHost
  - sudo sed -i -e "s,/var/www,$(pwd)/../deploy/public,g" /etc/apache2/sites-available/default
  - sudo sed -i -e "/DocumentRoot/i\ServerName test-selenium.dev" /etc/apache2/sites-available/default
  - echo "127.0.0.1 test-selenium.dev" | sudo tee -a /etc/hosts
  - sudo /etc/init.d/apache2 restart
#Run selenium
 - sh -e /etc/init.d/xvfb start
 - export DISPLAY=:99.0
 - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar
 - java -jar selenium-server-standalone-2.25.0.jar > /dev/null 2>&1 &
 - sleep 30

before_script:
# Create database
 - mysql -e 'create database `app-access-control-tests`;'
# Enter the tests folder
 - cd tests

script:
 - phpunit -d max_execution_time=0 
 - php ./coverage-checker.php ./clover.xml 100
