language: php

php:
 - "5.4"

before_install:
# Set the GitHub OAuth token to make use of the 6000 per hour rate limit
 - mkdir -p ~/.composer
 - cp .travis.composer.json ~/.composer/config.json
# Update composer
 - composer self-update
# Install project
 - composer install --dev -o
#deploy module
 - mkdir ../deploy
 - php ./vendor/bin/deploy_module.php -d ../deploy -v
#Define "default" sites-available
 - echo $(pwd)
 - cd ../deploy
 - sudo sed -i -e "s,/var/www,$(pwd)/public,g" /etc/apache2/sites-available/default
 - sudo /etc/init.d/apache2 restart
 - cd ../app-access-control
#Run selenium
 - "sh -e /etc/init.d/xvfb start"
 - "export DISPLAY=:99.0"
 - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar"
 - "java -jar selenium-server-standalone-2.25.0.jar > /dev/null 2>&1 &"
 - "sleep 30"

before_script:
# Create database
 - mysql -e 'create database `app-access-control-tests`;'
# Enter the tests folder
 - cd tests

script:
 - phpunit -d max_execution_time=0 
 - php ./coverage-checker.php ./clover.xml 100
