language: php

php:
 - 5.3.3
 - 5.3
 - 5.4

before_install:
 - composer self-update
 - composer install --dev

before_script:
 - cd tests
 - cp phpunit.xml.dist phpunit.xml

script:
 - phpunit
 - php ./tests/coverage-checker.php ./tests/clover.xml 100