language: php

php:
 - "5.4"

before_install:
 - composer self-update
 - composer install --dev -o

before_script:
 - echo 'max_execution_time = 500' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - mysql -e 'create database `app-access-control-tests`;'
 - cd tests

script:
 - phpunit
 - php ./coverage-checker.php ./clover.xml 100