<h3><?=$this->layout()->title?></h3>
<div class="well">
<?=$this->translate('new_user').' ? <a href="'.$this->url('AccessControl/Register').'">'.$this->translate('sign_up').'</a> ! | '.$this->translate('forgot_your_password').' ? <a href="'.$this->url('AccessControl/ForgottenCredential').'">'.$this->translate('reset_password').'</a>'?>
</div>
<?php
	if(!empty($this->error)){
		if($this->error === $this->translate('auth_access_pending'))$this->error .= '
			<br/><br/>
			<a href="javascript:oController.sendConfirmationEmail('.$this->escapeHtmlAttr($this->escapeJson($this->form->get('user_email')->getValue())).');">
				'.$this->translate('resend_confirmation_email').'
			</a>
		';
		echo $this->alert($this->error,'alert-error',false);
	}
	echo $this->form($this->form);
?>